# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: voicediary.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'voicediary.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10voicediary.proto\x12\nvoicediary\"a\n\x10SpeakerEmbedding\x12\x0e\n\x06vector\x18\x01 \x01(\x0c\x12\x16\n\x0e\x61udio_duration\x18\x02 \x01(\x02\x12\x12\n\nconfidence\x18\x03 \x01(\x02\x12\x11\n\ttimestamp\x18\x04 \x01(\x03\"\x8c\x01\n\x07Speaker\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x30\n\nembeddings\x18\x03 \x03(\x0b\x32\x1c.voicediary.SpeakerEmbedding\x12\x12\n\ncreated_at\x18\x04 \x01(\x03\x12\x12\n\nupdated_at\x18\x05 \x01(\x03\x12\r\n\x05\x63olor\x18\x06 \x01(\t\"\xab\x01\n\x0fTranscriptEntry\x12\x12\n\nspeaker_id\x18\x01 \x01(\x05\x12\x14\n\x0cspeaker_name\x18\x02 \x01(\t\x12\x0c\n\x04text\x18\x03 \x01(\t\x12\x10\n\x08language\x18\x04 \x01(\t\x12\x12\n\nstart_time\x18\x05 \x01(\x01\x12\x10\n\x08\x65nd_time\x18\x06 \x01(\x01\x12\x11\n\ttimestamp\x18\x07 \x01(\x03\x12\x15\n\rspeaker_color\x18\x08 \x01(\t\"\x7f\n\x11TranscriptSession\x12\x12\n\nsession_id\x18\x01 \x01(\t\x12\x14\n\x0csession_name\x18\x02 \x01(\t\x12,\n\x07\x65ntries\x18\x03 \x03(\x0b\x32\x1b.voicediary.TranscriptEntry\x12\x12\n\ncreated_at\x18\x04 \x01(\x03\"\x80\x01\n\x08Settings\x12\x15\n\rwhisper_model\x18\x01 \x01(\t\x12\x1c\n\x14similarity_threshold\x18\x02 \x01(\x02\x12\x10\n\x08language\x18\x03 \x01(\t\x12\x15\n\rvad_threshold\x18\x04 \x01(\x02\x12\x16\n\x0emax_embeddings\x18\x05 \x01(\x05\"Q\n\x0fSpeakerDatabase\x12%\n\x08speakers\x18\x01 \x03(\x0b\x32\x13.voicediary.Speaker\x12\x17\n\x0fnext_speaker_id\x18\x02 \x01(\x05\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'voicediary_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SPEAKEREMBEDDING']._serialized_start=32
  _globals['_SPEAKEREMBEDDING']._serialized_end=129
  _globals['_SPEAKER']._serialized_start=132
  _globals['_SPEAKER']._serialized_end=272
  _globals['_TRANSCRIPTENTRY']._serialized_start=275
  _globals['_TRANSCRIPTENTRY']._serialized_end=446
  _globals['_TRANSCRIPTSESSION']._serialized_start=448
  _globals['_TRANSCRIPTSESSION']._serialized_end=575
  _globals['_SETTINGS']._serialized_start=578
  _globals['_SETTINGS']._serialized_end=706
  _globals['_SPEAKERDATABASE']._serialized_start=708
  _globals['_SPEAKERDATABASE']._serialized_end=789
# @@protoc_insertion_point(module_scope)
