"""VoiceDiary — Classroom Lecture Note-Taking & Speaker Diarization AI.
VoiceDiary © Abdul Sarim Khan. All Rights Reserved.
Hugging Face Spaces Cloud Portfolio Edition.
"""
import os
import gc
import time
import tempfile
import numpy as np
import soundfile as sf
import gradio as gr

# Try importing Hugging Face ZeroGPU decorator
try:
    import spaces
    has_spaces = True
except ImportError:
    has_spaces = False

# Lazy-loaded model singletons
_transcriber = None
_embedder = None
_current_model_size = None

PAKISTANI_LECTURE_PROMPT = (
    "Bilingual Pakistani university classroom lecture in mixed English and Urdu. "
    "Discussion on computer science, concepts, formulas, code, assignments, presentations, questions and answers."
)


def get_transcriber(model_size="base"):
    global _transcriber, _current_model_size
    from faster_whisper import WhisperModel

    if _transcriber is None or _current_model_size != model_size:
        # Determine device and compute type
        import torch
        device = "cuda" if torch.cuda.is_available() else "cpu"
        compute_type = "float16" if device == "cuda" else "int8"
        cpu_threads = min(8, max(2, os.cpu_count() or 4))

        _transcriber = WhisperModel(
            model_size,
            device=device,
            compute_type=compute_type,
            cpu_threads=cpu_threads,
        )
        _current_model_size = model_size
    return _transcriber


def get_embedder():
    global _embedder
    if _embedder is None:
        from speechbrain.inference.speaker import EncoderClassifier
        import torch
        device = "cuda" if torch.cuda.is_available() else "cpu"
        with tempfile.TemporaryDirectory() as tmp:
            _embedder = EncoderClassifier.from_hparams(
                source="speechbrain/spkrec-ecapa-voxceleb",
                savedir=tmp,
                run_opts={"device": device},
            )
    return _embedder


def process_audio(audio_path, model_size, language_mode):
    """Processes uploaded or recorded audio for transcription & speaker diarization."""
    if not audio_path or not os.path.exists(audio_path):
        return "⚠️ No audio provided. Please record or upload an audio file.", "", ""

    t_start = time.time()
    try:
        # 1. Load and resample audio to 16kHz mono float32
        data, sr = sf.read(audio_path)
        if data.ndim > 1:
            data = data.mean(axis=1)
        data = data.astype(np.float32)

        if sr != 16000:
            from scipy.signal import resample_poly
            gcd = int(np.gcd(16000, sr))
            data = resample_poly(data, 16000 // gcd, sr // gcd).astype(np.float32)

        total_duration = len(data) / 16000.0

        # 2. Transcribe using Whisper
        model = get_transcriber(model_size)
        target_lang = None if language_mode in ["auto", "bilingual"] else language_mode

        segments, info = model.transcribe(
            data,
            beam_size=5 if model_size in ["tiny", "base"] else 3,
            language=target_lang,
            initial_prompt=PAKISTANI_LECTURE_PROMPT,
            vad_filter=True,
            vad_parameters=dict(min_silence_duration_ms=400),
            word_timestamps=False,
        )

        # 3. Speaker Diarization with ECAPA-TDNN
        speaker_profiles = {}  # id: list of embeddings
        speaker_colors = ["#6366F1", "#10B981", "#F59E0B", "#EF4444", "#EC4899", "#8B5CF6"]
        next_speaker_id = 1

        transcript_entries = []
        md_lines = [
            f"# 🎙️ VoiceDiary Lecture Notes",
            f"*Generated by VoiceDiary AI © Abdul Sarim Khan*",
            f"**Model:** `{model_size}` | **Detected Language:** `{info.language.upper()}` | **Audio Duration:** `{total_duration:.1f}s`\n",
            "---\n",
        ]
        txt_lines = [f"VoiceDiary Lecture Notes (Duration: {total_duration:.1f}s)\n"]

        for seg in segments:
            text = seg.text.strip()
            if not text:
                continue

            start_s = seg.start
            end_s = seg.end
            seg_audio = data[int(start_s * 16000): int(end_s * 16000)]

            # Speaker identification
            spk_id = 1
            if len(seg_audio) >= 8000:  # At least 0.5s for speaker embedding
                try:
                    emb_model = get_embedder()
                    import torch
                    with torch.inference_mode():
                        waveform = torch.from_numpy(seg_audio).float().unsqueeze(0)
                        if hasattr(emb_model, 'device') and emb_model.device:
                            waveform = waveform.to(emb_model.device)
                        emb = emb_model.encode_batch(waveform).squeeze().detach().cpu().numpy()
                        emb_norm = emb / np.linalg.norm(emb)

                    # Match with existing speakers
                    best_id = None
                    best_sim = -1.0
                    for s_id, embs in speaker_profiles.items():
                        sims = [float(np.dot(emb_norm, e)) for e in embs]
                        max_s = max(sims) if sims else 0
                        if max_s > best_sim:
                            best_sim = max_s
                            best_id = s_id

                    if best_id and best_sim >= 0.72:
                        spk_id = best_id
                        if len(speaker_profiles[spk_id]) < 50:
                            speaker_profiles[spk_id].append(emb_norm)
                    else:
                        spk_id = next_speaker_id
                        speaker_profiles[spk_id] = [emb_norm]
                        next_speaker_id += 1
                except Exception:
                    pass

            spk_color = speaker_colors[(spk_id - 1) % len(speaker_colors)]
            time_str = f"{int(start_s // 60):02d}:{int(start_s % 60):02d}"

            # Format for Gradio Markdown display
            md_lines.append(
                f"<div style='margin-bottom: 12px; padding: 10px 14px; border-left: 4px solid {spk_color}; background: rgba(255,255,255,0.03); border-radius: 6px;'>"
                f"<strong style='color: {spk_color};'>Speaker {spk_id}</strong> <span style='font-size: 11px; opacity: 0.6; margin-left: 8px;'>[{time_str}]</span><br/>"
                f"<span style='font-size: 14px; margin-top: 4px; display: inline-block;'>{text}</span>"
                f"</div>"
            )
            txt_lines.append(f"[{time_str}] Speaker {spk_id}: {text}")

        elapsed = time.time() - t_start
        md_lines.append(f"\n---\n*⚡ Processed in {elapsed:.2f}s ({total_duration/max(0.01, elapsed):.1f}x real-time speed)*")

        full_md = "\n".join(md_lines)
        full_txt = "\n".join(txt_lines)

        # Save downloadable files
        with tempfile.NamedTemporaryFile(mode="w", suffix=".md", delete=False, encoding="utf-8") as f_md:
            f_md.write(full_md)
            md_path = f_md.name

        with tempfile.NamedTemporaryFile(mode="w", suffix=".txt", delete=False, encoding="utf-8") as f_txt:
            f_txt.write(full_txt)
            txt_path = f_txt.name

        return full_md, md_path, txt_path

    except Exception as ex:
        return f"❌ Error during transcription: {ex}", None, None


# Apply ZeroGPU acceleration decorator if running on Hugging Face Spaces
if has_spaces:
    process_audio = spaces.GPU(process_audio)

# Gradio Interface Definition
custom_css = """
body { background-color: #0F172A; color: #F8FAFC; font-family: 'Segoe UI', system-ui, sans-serif; }
.gradio-container { max-width: 900px !important; margin: 0 auto !important; }
.header-box { text-align: center; padding: 24px 0 16px; }
.header-box h1 { font-size: 28px; font-weight: 700; color: #F59E0B; margin-bottom: 4px; }
.header-box p { font-size: 14px; color: #94A3B8; }
.badge { display: inline-block; background: rgba(245, 158, 11, 0.15); border: 1px solid #F59E0B; color: #F59E0B; padding: 3px 10px; border-radius: 9999px; font-size: 11px; font-weight: 600; margin-top: 6px; }
"""

with gr.Blocks(title="VoiceDiary AI — Classroom Lecture Diarization", css=custom_css, theme=gr.themes.Default(primary_hue="amber", neutral_hue="slate")) as demo:
    with gr.Column(elem_classes=["header-box"]):
        gr.Markdown("# VoiceDiary")
        gr.Markdown("**Bilingual Classroom Lecture Note-Taking & Speaker Diarization AI**")
        gr.Markdown("<span class='badge'>VoiceDiary © Abdul Sarim Khan. All Rights Reserved.</span>")

    with gr.Row():
        with gr.Column(scale=1):
            audio_input = gr.Audio(sources=["microphone", "upload"], type="filepath", label="Record Speech or Upload Audio File (.mp3, .wav, .m4a)")
            
            with gr.Row():
                model_dropdown = gr.Dropdown(
                    choices=["tiny", "base", "small", "medium", "large-v3-turbo", "distil-large-v3"],
                    value="base",
                    label="Whisper Speech Model",
                    info="Base is recommended for fast real-time bilingual lectures."
                )
                lang_dropdown = gr.Dropdown(
                    choices=["auto", "ur", "en"],
                    value="auto",
                    label="Language Mode",
                    info="Auto handles mixed Urdu + English bilingual classroom speech."
                )

            submit_btn = gr.Button("Transcribe & Diarize Lecture", variant="primary", size="lg")

        with gr.Column(scale=1):
            transcript_output = gr.Markdown(label="Lecture Notes & Diarized Transcript", value="*Your diarized lecture transcript will appear here...*")
            
            with gr.Row():
                download_md = gr.File(label="Download Markdown Notes (.md)")
                download_txt = gr.File(label="Download Plain Text (.txt)")

    submit_btn.click(
        fn=process_audio,
        inputs=[audio_input, model_dropdown, lang_dropdown],
        outputs=[transcript_output, download_md, download_txt],
    )

if __name__ == "__main__":
    demo.launch()
