"""AI Lecture Summarization and Flashcard Generation using Google Gemini 2.5 Flash.
VoiceDiary © Abdul Sarim Khan. All Rights Reserved.
"""
import os
import json
import logging
import urllib.request
import urllib.error
from typing import Dict, Any, List

logger = logging.getLogger(__name__)

DEFAULT_GEMINI_API_KEY = ""


class GeminiSummarizer:
    """Generates structured classroom lecture summaries, key takeaways,
    exam revision flashcards, and action items using Gemini 2.5 Flash.
    """

    def __init__(self, api_key: str = None):
        key = api_key
        if not key:
            try:
                from config import get_user_data_dir
                import json
                settings_file = get_user_data_dir() / "settings.json"
                if settings_file.exists():
                    s = json.loads(settings_file.read_text(encoding="utf-8"))
                    key = s.get("gemini_api_key", "")
            except Exception:
                pass

        if not key:
            key = os.environ.get("GEMINI_API_KEY", "") or DEFAULT_GEMINI_API_KEY

        self.api_key = key.strip() if key else ""

    def summarize_lecture(self, transcript_entries: List[Dict[str, Any]], lecture_title: str = "Classroom Lecture") -> Dict[str, Any]:
        """Summarizes a full lecture session into structured markdown."""
        if not transcript_entries:
            return {"success": False, "message": "No transcript content to summarize."}

        if not self.api_key:
            return {
                "success": False,
                "message": "Gemini API Key is not set. Please add your free key in Settings (get one free in 30s at aistudio.google.com)."
            }

        # Format transcript lines for prompt
        lines = []
        for e in transcript_entries:
            spk = e.get("speaker_name", "Speaker")
            time_str = e.get("timestamp", "")
            text = e.get("text", "").strip()
            if text:
                prefix = f"[{time_str}] {spk}: " if time_str else f"{spk}: "
                lines.append(f"{prefix}{text}")

        full_transcript = "\n".join(lines)
        if len(full_transcript) < 30:
            return {"success": False, "message": "Transcript is too short to generate a meaningful summary."}

        system_instruction = (
            "You are an expert academic AI note-taker and university study assistant for 'VoiceDiary'. "
            "Your task is to analyze bilingual Pakistani university lectures (mixed English and Urdu) "
            "and generate structured, publication-quality lecture study notes.\n\n"
            "Format the output in clean Markdown using these exact sections:\n"
            "1. 📌 **Executive Lecture Summary** (3-4 concise bullet points of main themes)\n"
            "2. 🎯 **Key Concepts & Mathematical Formulas** (Deep dive into definitions, formulas, code, concepts)\n"
            "3. 💡 **Study Flashcards & Exam Q&A** (5 question and answer pairs for fast exam revision)\n"
            "4. 📋 **Action Items & Homework Mentioned** (Any assignments, tasks, deadlines, or readings given by the instructor)\n\n"
            "If any terms were spoken in Roman Urdu, explain their academic concept clearly in English and Urdu."
        )

        user_prompt = f"Lecture Title: {lecture_title}\n\nTranscript Content:\n{full_transcript}"

        url = f"https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?key={self.api_key}"

        payload = {
            "contents": [
                {
                    "parts": [
                        {"text": f"{system_instruction}\n\n{user_prompt}"}
                    ]
                }
            ],
            "generationConfig": {
                "temperature": 0.3,
                "topP": 0.95,
                "maxOutputTokens": 2048,
            }
        }

        try:
            req = urllib.request.Request(
                url,
                data=json.dumps(payload).encode("utf-8"),
                headers={"Content-Type": "application/json"}
            )

            with urllib.request.urlopen(req, timeout=25) as response:
                res_data = json.loads(response.read().decode("utf-8"))
                candidates = res_data.get("candidates", [])
                if not candidates:
                    return {"success": False, "message": "Gemini returned an empty response."}

                summary_text = candidates[0].get("content", {}).get("parts", [{}])[0].get("text", "")
                logger.info("AI Lecture Summary successfully generated by Gemini 2.5 Flash.")
                return {
                    "success": True,
                    "summary_markdown": summary_text,
                    "model": "gemini-2.5-flash"
                }

        except urllib.error.HTTPError as he:
            err_msg = he.read().decode("utf-8", errors="ignore")
            logger.error("Gemini API HTTP Error %d: %s", he.code, err_msg)
            return {"success": False, "message": f"Gemini API Error ({he.code}): {err_msg}"}
        except Exception as ex:
            logger.error("Gemini summarization failed: %s", ex)
            return {"success": False, "message": f"Failed to generate summary: {str(ex)}"}
